// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLFB5CBmsn_sqEM8MdFnuQH_f9QQCfuo',
    appId: '1:125470200443:web:6dcb216948c0d42a8748de',
    messagingSenderId: '125470200443',
    projectId: 'jolga-16c48',
    authDomain: 'jolga-16c48.firebaseapp.com',
    storageBucket: 'jolga-16c48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNYwBNBJSuQIhNAtloX926v4svmwUsRLY',
    appId: '1:125470200443:android:ee4629ff627649048748de',
    messagingSenderId: '125470200443',
    projectId: 'jolga-16c48',
    storageBucket: 'jolga-16c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOKPAcQ3KCchk3296Mnfu08F2sWyVn-Q0',
    appId: '1:125470200443:ios:b5cd0b4a0ed5b8c88748de',
    messagingSenderId: '125470200443',
    projectId: 'jolga-16c48',
    storageBucket: 'jolga-16c48.appspot.com',
    iosClientId: '125470200443-iedta2h1cmivhltdp9r4ghtv4pai1lrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOKPAcQ3KCchk3296Mnfu08F2sWyVn-Q0',
    appId: '1:125470200443:ios:b5cd0b4a0ed5b8c88748de',
    messagingSenderId: '125470200443',
    projectId: 'jolga-16c48',
    storageBucket: 'jolga-16c48.appspot.com',
    iosClientId: '125470200443-iedta2h1cmivhltdp9r4ghtv4pai1lrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.jl',
  );
}
